require 'curses'
require 'tco'
require 'rmagick'
require 'io/console'

require 'strokes/version'
require 'strokes/role'
require 'strokes/data_source'
require 'strokes/window'
require 'strokes/panel'
require 'strokes/layout'
